( define ( problem problem_1 )
( :domain gripper-domain )
( :objects
	box_a1 box_a2 box_b1 box_b2 box_c1 box_c2 - box
	start base_1 base_2 base_3 base_a base_b base_c - stackbase
	deposit_a deposit_b deposit_c - deposit
	gripper_a - gripper
	carrier_a carrier_b carrier_c - carrier
)
( :init
	( upon gripper_a start )
	( on box_a1 base_1 base_1 )
	( on box_c2 box_a1 base_1 )
	( on box_a2 box_c2 base_1 )
	( in box_a1 base_1 )
	( in box_c2 base_1 )
	( in box_a2 base_1 )
	( in base_1 base_1 )
	( clear box_a2 )
	( on box_b1 base_2 base_2 )
	( on box_b2 box_b1 base_2 )
	( on box_c1 box_b2 base_2 )
	( in box_b1 base_2 )
	( in box_b2 base_2 )
	( in box_c1 base_2 )
	( in base_2 base_2 )
	( clear box_c1 )
	( clear base_3 )
	( clear base_c )
	( clear base_b )
	( clear base_a )
	( in base_a base_a )
	( in base_b base_b )
	( in base_c base_c )
	( in base_3 base_3 )
	( carrier_in_deposit carrier_a deposit_a )
	( carrier_in_deposit carrier_b deposit_b )
	( carrier_in_deposit carrier_c deposit_c )
	( carrier_can_come carrier_a base_a )
	( carrier_can_come carrier_b base_b )
	( carrier_can_come carrier_c base_c )
	( carrier_can_go carrier_a deposit_a )
	( carrier_can_go carrier_b deposit_b )
	( carrier_can_go carrier_c deposit_c )
	( = ( holding_boxes gripper_a ) 0.0000000000 )
	( = ( stacked base_1 ) 3.0000000000 )
	( = ( stacked base_2 ) 3.0000000000 )
	( = ( stacked base_3 ) 0.0000000000 )
	( = ( stacked base_a ) 0.0000000000 )
	( = ( stacked base_b ) 0.0000000000 )
	( = ( stacked base_c ) 0.0000000000 )
	( = ( moving_boxes carrier_a ) 0.0000000000 )
	( = ( moving_boxes carrier_b ) 0.0000000000 )
	( = ( moving_boxes carrier_c ) 0.0000000000 )
)
( :goal
	( and
		( upon gripper_a start )
		( carrier_moving carrier_a box_a1 )
		( carrier_moving carrier_a box_a2 )
		( carrier_moving carrier_b box_b1 )
		( carrier_moving carrier_b box_b2 )
		( carrier_moving carrier_c box_c1 )
		( carrier_moving carrier_c box_c2 )
	)
)
)
