AGENT_ID_PARAM = 'agent_id'
AGENT_GROUP_ID_PARAM = 'agent_group'
PDDL_FILE_PARAM = 'pddl_file'

INIT_BSET_PARAM = 'init_bset'
INIT_DSET_PARAM = 'init_dset'
INIT_RRULESSET_PARAM = 'init_reactive_rules_set'

ACCEPT_BELIEFS_R_PARAM = 'belief_ck'
ACCEPT_BELIEFS_W_PARAM = 'belief_w'
ACCEPT_DESIRES_R_PARAM = 'desire_ck'
ACCEPT_DESIRES_W_PARAM = 'desire_w'
ACCEPT_DESIRES_MAX_PR_PARAM = 'desire_pr'

ABORT_SURPASS_DEADLINE_DEADLINE_PARAM = 'rtc_deadline'
COMP_PLAN_TRIES_PARAM = 'comp_plan_tries'
EXEC_PLAN_TRIES_PARAM = 'exec_plan_tries'

AUTOSUBMIT_PREC_PARAM = 'autosub_prec'
AUTOSUBMIT_CONTEXT_PARAM = 'autosub_context'

RESCHEDULE_POLICY_PARAM = 'reschedule_policy'
RESCHEDULE_POLICY_VAL_NO_IF_EXEC = 'NO_PREEMPT'
RESCHEDULE_POLICY_VAL_IF_EXEC = 'PREEMPT'

DEBUG_PARAM = 'debug'
DEBUG_ACTIVE_NODES_PARAM = 'debug_log_active'