# This is DelDesire service message used to request among agents to delete desire in their desire set
# returns accepted = true if they are not there or successfully removed

# @desire           -> desire to be added to agent's desire set
# @agent_group      -> requesting agent's group
# ---
# @accepted         -> request accepted by agent

Desire desire
string agent_group
---
bool   accepted