# This is UpdBeliefSet service message used to request among agents to push/delete new/old belief in their belief set
# returns accepted = true if request accepted
# returns updated  = true if accepted AND they are (already) there or successfully added in case of addition requested

# @belief           -> belief to be added to agent's belief set
# @agent_group      -> requesting agent's group
# ---
# @accepted         -> request accepted by agent

Belief belief
string agent_group
---
bool   accepted
bool   updated