# This is UpdDesireSet service message used to request among agents to push/delete new/old desire in their desire set
# returns accepted = true if request accepted
# returns updated  = true if accepted AND they are (already) there or successfully added in case of addition requested

# @desire           -> desire to be added to agent's desire set
# @agent_group      -> requesting agent's group
# ---
# @accepted         -> request accepted by agent

Desire desire
string agent_group
---
bool   accepted
bool   updated